project:
  type: website
  output-dir: docs
website:
  title: "nadia"
  navbar:
    background: "#ffffff"
    logo: logo.svg
    left:
      - href: index.qmd
        text: "Nosotros"
      - href: encuesta.qmd
        text: "Investigaci√≥n"  
    right:
      - icon: github
        href: https://github.com/cepe-fundar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



